<?php

namespace App\Filament\Resources;

use App\Filament\Resources\DocumentResource\Pages;
use App\Models\Deal;
use App\Models\Document;
use App\Models\Lead;
use App\Models\Property;
use Barryvdh\DomPDF\Facade\Pdf;
use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\Section;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class DocumentResource extends Resource
{
    protected static ?string $model = Document::class;

    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static ?string $navigationGroup = 'Productivity';

    protected static ?int $navigationSort = 5;

    public static function form(Form $form): Form
    {
        return $form->schema([
            Section::make('Document Details')->columns(2)->schema([
                TextInput::make('title')->required(),
                Select::make('template_type')
                    ->label('Template')
                    ->options([
                        'offer_letter'       => 'Offer Letter',
                        'contract'           => 'Purchase & Sale Contract',
                        'property_info_sheet'=> 'Property Info Sheet',
                    ])
                    ->required(),
                Select::make('lead_id')
                    ->label('Lead / Seller')
                    ->options(fn () => Lead::orderBy('owner_name')->whereNotNull('owner_name')->pluck('owner_name', 'id')->toArray())
                    ->searchable(),
                Select::make('deal_id')
                    ->label('Deal')
                    ->options(fn () => Deal::orderBy('name')->whereNotNull('name')->pluck('name', 'id')->toArray())
                    ->searchable(),
                Select::make('property_id')
                    ->label('Property')
                    ->options(fn () => Property::orderBy('address')->whereNotNull('address')->pluck('address', 'id')->toArray())
                    ->searchable(),
            ]),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('title')->searchable()->sortable(),
                Tables\Columns\BadgeColumn::make('template_type')
                    ->label('Template')
                    ->formatStateUsing(fn ($state) => match ($state) {
                        'offer_letter'        => 'Offer Letter',
                        'contract'            => 'Contract',
                        'property_info_sheet' => 'Info Sheet',
                        default               => $state,
                    }),
                Tables\Columns\TextColumn::make('lead.owner_name')->label('Lead')->limit(30),
                Tables\Columns\TextColumn::make('deal.name')->label('Deal')->limit(25),
                Tables\Columns\TextColumn::make('generatedBy.name')->label('Generated By'),
                Tables\Columns\TextColumn::make('generated_at')->dateTime()->sortable()->label('Generated'),
                Tables\Columns\IconColumn::make('path')
                    ->label('PDF')
                    ->boolean()
                    ->trueIcon('heroicon-o-document-arrow-down')
                    ->falseIcon('heroicon-o-x-circle'),
            ])
            ->defaultSort('created_at', 'desc')
            ->actions([
                Tables\Actions\Action::make('generate_pdf')
                    ->label('Generate PDF')
                    ->icon('heroicon-o-arrow-down-tray')
                    ->color('success')
                    ->action(function (Document $record) {
                        $lead     = $record->lead;
                        $deal     = $record->deal;
                        $property = $record->property ?? $lead?->properties()->first();
                        $company  = auth()->user()?->team?->name ?? 'Pro Real Estate Investments';

                        $view = match ($record->template_type) {
                            'offer_letter'        => 'pdf.offer-letter',
                            'contract'            => 'pdf.contract',
                            'property_info_sheet' => 'pdf.property-info-sheet',
                            default               => 'pdf.offer-letter',
                        };

                        $pdf = Pdf::loadView($view, compact('lead', 'deal', 'property', 'company'));

                        $filename = Str::slug($record->title) . '-' . now()->format('Ymd-His') . '.pdf';
                        $path = 'documents/' . $filename;

                        Storage::disk('local')->put($path, $pdf->output());

                        $record->update([
                            'path'         => $path,
                            'generated_at' => now(),
                            'generated_by' => auth()->id(),
                        ]);

                        Notification::make()->title('PDF generated: ' . $filename)->success()->send();

                        return response()->streamDownload(
                            fn () => print($pdf->output()),
                            $filename,
                            ['Content-Type' => 'application/pdf']
                        );
                    }),
                Tables\Actions\Action::make('download')
                    ->label('Download')
                    ->icon('heroicon-o-document-arrow-down')
                    ->visible(fn (Document $record) => (bool) $record->path)
                    ->action(function (Document $record) {
                        $content = Storage::disk('local')->get($record->path);
                        return response()->streamDownload(
                            fn () => print($content),
                            basename($record->path),
                            ['Content-Type' => 'application/pdf']
                        );
                    }),
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index'  => Pages\ListDocuments::route('/'),
            'create' => Pages\CreateDocument::route('/create'),
            'edit'   => Pages\EditDocument::route('/{record}/edit'),
        ];
    }
}
